<a href="https://colab.research.google.com/github/aritrasen87/LLM_From_Scratch/blob/main/1_LLM_From_Scratch_PytorchEssentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pytorch Essentials for Buildilng LLM from Scratch - https://www.youtube.com/@AritraSen

Deep learning with Pytorch: https://youtube.com/playlist?list=PLOrU905yPYXJsJSHJsiE779KfcrRCgz4v&si=kMm_xrDwfKF9mVCk

In [1]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cpu


In [3]:
tensor1 = torch.randn(4, 5)
tensor2 = torch.randn(5, 4)

In [4]:
tensor1.shape , tensor2.shape

(torch.Size([4, 5]), torch.Size([5, 4]))

In [5]:
print(tensor1)

tensor([[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]])


In [6]:
print(tensor2)

tensor([[ 0.0487, -0.2556,  0.6114, -0.9860],
        [ 2.0516,  0.8587,  0.1332, -1.0107],
        [ 0.4745, -1.7851,  1.1327,  0.5256],
        [ 0.1034, -1.3270, -0.3440, -0.1356],
        [ 1.7968,  1.1401,  0.8945,  0.8371]])


### Dot Product

In [7]:
tensor3 = tensor1 @ tensor2
print(tensor3)

tensor([[ 1.8893,  6.0983, -0.8972,  0.4140],
        [ 1.3523, -3.8964,  1.8957,  0.0790],
        [ 2.7581,  0.3025,  0.4781, -1.0870],
        [ 1.0380,  3.0645, -1.5491, -1.4147]])


In [8]:
torch.matmul(tensor1,tensor2)

tensor([[ 1.8893,  6.0983, -0.8972,  0.4140],
        [ 1.3523, -3.8964,  1.8957,  0.0790],
        [ 2.7581,  0.3025,  0.4781, -1.0870],
        [ 1.0380,  3.0645, -1.5491, -1.4147]])

### Concatination

In [9]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4])
torch.cat((t1,t2),dim=0)

tensor([1, 2, 3, 4])

In [12]:
tensor1

tensor([[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]])

In [10]:
torch.cat((tensor1,tensor1),dim=0)

tensor([[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142],
        [-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]])

In [11]:
torch.cat((tensor1,tensor1),dim=1)

tensor([[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301, -0.3210,  0.1555, -1.9451,
         -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078,  0.9635, -0.1619,  1.2123,
          1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611, -0.4957,  1.6155,  0.7247,
         -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142,  0.0725,  0.6554, -1.5434,
          0.3611,  0.2142]])

In [13]:
torch.stack([tensor1,tensor1])

tensor([[[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
         [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
         [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
         [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]],

        [[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
         [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
         [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
         [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]]])

### nn.Multinomial

In [14]:
# torch.multinomial(input, num_samples, replacement=False, *, generator=None, out=None) → LongTensor

# Parameters:
    # input (Tensor) – the input tensor containing probabilities

    # num_samples (int) – number of samples to draw

    # replacement (bool, optional) – whether to draw with replacement or not

probabilities = torch.tensor([0.1, 0.4 , 0.5]) # 10% => 0, 40%=> 1 , 50% for 2 ,  each probability points to the index of the probability in the tensor

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 2, 2, 2, 2, 2, 0, 1, 1])


### Trail Matrix

Returns the lower triangular part of the matrix (2-D tensor) or batch of matrices input, the other elements of the result tensor out are set to 0.

In [15]:
print(tensor1)

tensor([[-0.3210,  0.1555, -1.9451, -0.5879,  1.4301],
        [ 0.9635, -0.1619,  1.2123,  1.4513,  0.5078],
        [-0.4957,  1.6155,  0.7247, -0.4581, -0.4611],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.2142]])


In [16]:
print(torch.tril(tensor1))

tensor([[-0.3210,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.9635, -0.1619,  0.0000,  0.0000,  0.0000],
        [-0.4957,  1.6155,  0.7247,  0.0000,  0.0000],
        [ 0.0725,  0.6554, -1.5434,  0.3611,  0.0000]])


In [17]:
tensor1.shape

torch.Size([4, 5])

In [18]:
out = tensor1.masked_fill(torch.tril(torch.ones(4, 5)) == 0, float('-inf'))
out

tensor([[-0.3210,    -inf,    -inf,    -inf,    -inf],
        [ 0.9635, -0.1619,    -inf,    -inf,    -inf],
        [-0.4957,  1.6155,  0.7247,    -inf,    -inf],
        [ 0.0725,  0.6554, -1.5434,  0.3611,    -inf]])

### Transpose

In [19]:
t3 = torch.rand(2,3,4)
t3.shape

torch.Size([2, 3, 4])

In [20]:
t3

tensor([[[0.3344, 0.6053, 0.9161, 0.0449],
         [0.2004, 0.2119, 0.1828, 0.1678],
         [0.8726, 0.7925, 0.6577, 0.6335]],

        [[0.1122, 0.9511, 0.1695, 0.9367],
         [0.8109, 0.6925, 0.9848, 0.0338],
         [0.4634, 0.6927, 0.9403, 0.4653]]])

In [21]:
t3.transpose(0,1).shape

torch.Size([3, 2, 4])

### nn.Embedding

In [22]:
# Initialize an embedding layer
vocab_size = 50
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 0, 5])

# Apply the embedding layer
embedded_output = embedding(input_indices)

print(embedded_output.shape)  # no of tokens * embedding dimension

torch.Size([3, 100])


In [23]:
print(embedded_output[0].shape)

torch.Size([100])
